"""Build deck.json — the single source of content for Rot Check.

    python tools/make-deck.py

Writes ios/RotCheck/deck.json. Bump VERSION whenever the content changes;
DeckLoader only replaces a cached deck with a strictly newer version.

Content rules (13+ rating):
  - no real people's names
  - no sexual terms, no slurs, no drug references
  - "real" means widely used online 2020-2026; when in doubt, it's left out
  - "fake" means invented for this deck; near-misses of real terms are the
    best ones, and get tricky=True so they roll better High Rot odds
"""
import io
import json
import os
import re
import sys

VERSION = 2
UPDATED = "2026-09-01"
OUT = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                   "ios", "RotCheck", "deck.json")

# (term, note, tricky)
REAL = [
    # ── the core ──────────────────────────────────────────────────────────
    ("skibidi", "From the Skibidi Toilet series. Means roughly nothing, deployed constantly.", False),
    ("rizz", "Charisma, the flirting kind.", False),
    ("gyatt", "An exclamation of shock. Streamer-born, now everywhere.", False),
    ("fanum tax", "Taxing a friend's food. Named after a streamer's habit.", False),
    ("sigma", "The lone-wolf archetype. Almost always ironic now.", False),
    ("mewing", "Tongue-to-palate jaw posture. A whole subculture.", False),
    ("mogging", "Out-attractive-ing someone just by standing near them.", False),
    ("looksmaxxing", "Optimising your appearance with unsettling intensity.", False),
    ("delulu", "Delusional, affectionately.", False),
    ("aura", "Coolness as a stat.", False),
    ("aura points", "An imaginary scoreboard for how cool an action was.", True),
    ("aura farming", "Doing things purely to look cool.", True),
    ("negative aura", "The opposite. Losing points for being cringe.", True),
    ("crashing out", "Losing it emotionally, publicly, on purpose.", False),
    ("crashout", "Same thing, as a noun.", False),
    ("glazing", "Praising someone way past the point of dignity.", False),
    ("cooked", "Finished. Doomed. No recovery available.", False),
    ("chopped", "Unattractive, or badly beaten at something.", False),
    ("yapping", "Talking far too much.", False),
    ("yap session", "A long stretch of talking far too much.", True),
    ("NPC", "Someone on autopilot with stock dialogue.", False),
    ("touch grass", "Go outside. You have been extremely online.", False),
    ("ratio", "Your reply outperformed the post. Devastating.", False),
    ("it's giving", "It evokes. It resembles. Ballroom slang gone global.", True),
    ("bussin", "Genuinely delicious.", False),
    ("clanker", "A robot, said with disdain.", True),
    ("six seven", "Say it with the hand gesture. Nobody knows why.", True),
    ("huzz", "Girls, plural. Don't ask about the etymology.", True),
    ("bruzz", "The bros. Same pattern.", True),
    ("opps", "Your enemies.", True),
    ("lock in", "Focus completely.", True),
    ("locked in", "Fully focused. Nothing else exists.", False),
    ("twin", "Close friend. 'Twin, what happened?'", True),
    ("gng", "Gang, as a form of address.", True),
    ("blud", "Bro, UK edition.", True),
    ("cuh", "Bro, Southern edition.", True),
    ("unc", "Anyone over 25. Short for uncle.", True),
    ("unc status", "Officially old.", True),
    ("big back", "Someone who eats a lot. Said with love, usually.", True),
    ("tuff", "Cool. 'That's tuff.'", True),
    ("fye", "Fire. Extremely good.", True),
    ("icl", "I can't lie.", True),
    ("ong", "On God.", False),
    ("fr", "For real.", False),
    ("frfr", "For real for real.", False),
    ("deadass", "Seriously.", False),
    ("no cap", "No lie.", False),
    ("cap", "A lie.", False),
    ("capping", "Lying.", False),
    ("bet", "Okay. Deal.", False),
    ("say less", "Understood, no need to continue.", False),
    ("lowkey", "Slightly, or secretly.", False),
    ("highkey", "Very, or openly.", False),
    ("mid", "Aggressively average. The cruellest rating.", False),
    ("bum", "A loser.", False),
    ("bummy", "Looking like a bum.", True),
    ("goofy ahh", "Silly-looking. 'Goofy ahh haircut.'", True),
    ("ahh", "A suffix. Censored, but everyone knows.", True),
    ("ohio", "Anywhere weird.", False),
    ("only in ohio", "Where the cursed things happen.", False),
    ("ohio final boss", "The weirdest possible thing in Ohio.", True),
    ("final boss", "The ultimate version of something.", False),
    ("rizzler", "Someone with rizz.", False),
    ("skibidi rizz", "Compound nonsense. Real usage though.", True),
    ("sussy", "Suspicious. Among Us era.", False),
    ("sus", "Suspicious.", False),
    ("baka", "Idiot, borrowed from anime.", True),
    ("amogus", "Among Us, mutated by memes.", True),
    ("skill issue", "Your fault. Get better.", False),
    ("git gud", "Get good.", True),
    ("GG", "Good game.", False),
    ("ez", "Easy. Said specifically to annoy.", False),
    ("took the L", "Accepted the loss.", False),
    ("L + ratio", "The full dismissal combo.", True),
    ("bozo", "A clown.", False),
    ("cringe", "Embarrassing.", False),
    ("based", "Unapologetically yourself.", False),
    ("cope", "Denial with extra steps.", False),
    ("seethe", "Be angry, impotently.", True),
    ("mald", "Mad plus bald. Rage so intense you lose hair.", True),
    ("salty", "Bitter about a loss.", False),
    ("pressed", "Upset.", False),
    ("triggered", "Upset, said ironically.", False),
    ("let him cook", "Stand back. He might be onto something.", True),
    ("he cooked", "He did great.", False),
    ("cooking", "Doing great, in progress.", False),
    ("ate", "Did amazingly.", False),
    ("ate and left no crumbs", "Did amazingly, completely.", False),
    ("served", "Delivered a look or a performance.", False),
    ("slay", "Do amazingly.", False),
    ("mother", "An iconic woman.", True),
    ("mother is mothering", "Peak iconic.", True),
    ("iconic", "Memorable. Legendary.", False),
    ("understood the assignment", "Did exactly what was needed.", False),
    ("main character", "The protagonist.", False),
    ("main character energy", "Acting like the protagonist.", False),
    ("villain era", "A phase of not being nice.", False),
    ("era", "A phase.", False),
    ("flop", "A failure.", False),
    ("flop era", "A phase of failing.", True),
    ("rent free", "Occupying your thoughts, uninvited.", False),
    ("vibe check", "An assessment of the mood.", False),
    ("vibing", "Enjoying the moment.", False),
    ("simp", "Someone excessively devoted to a crush.", False),
    ("stan", "An intense fan.", False),
    ("the ick", "A sudden, permanent turn-off.", False),
    ("beige flag", "A boring but harmless trait.", True),
    ("red flag", "A warning sign.", False),
    ("green flag", "A good sign.", False),
    ("ghosting", "Vanishing from a conversation.", False),
    ("breadcrumbing", "Giving minimal attention to keep someone hooked.", True),
    ("situationship", "A relationship without a label.", False),
    ("talking stage", "The pre-dating phase.", False),
    ("soft launch", "Hinting at a relationship on social media.", True),
    ("hard launch", "Officially revealing a relationship.", True),
    ("roster", "The people you're talking to.", True),
    ("down bad", "Desperately infatuated.", False),
    ("down horrendous", "Even more so.", True),
    ("feral", "Wild. Unhinged.", False),
    ("unhinged", "Chaotic.", False),
    ("chronically online", "Too much internet.", False),
    ("terminally online", "Even more internet.", True),
    ("brainrot", "What this game is about.", False),
    ("doomscrolling", "Endless bad-news scrolling.", False),
    ("bed rotting", "Lying in bed all day, on purpose.", True),
    ("goblin mode", "Unapologetically slobby.", False),
    ("gremlin", "Chaotic little creature energy.", False),
    ("lore", "Backstory.", False),
    ("lore drop", "Backstory, revealed.", False),
    ("canon event", "An unavoidable, formative moment.", True),
    ("filler arc", "A stretch of life that doesn't advance the plot.", True),
    ("core memory", "A defining memory.", False),
    ("cottagecore", "The aesthetic suffix, in its original habitat.", True),
    ("coquette", "Bows, lace, ribbons.", True),
    ("clean girl", "Minimal makeup, slicked-back bun.", True),
    ("demure", "Modest. 'Very demure, very mindful.'", True),
    ("very demure very mindful", "The full phrase.", True),
    ("brat summer", "Summer 2024, specifically.", True),
    ("girl dinner", "A snack plate as a meal.", True),
    ("girl math", "Justifying purchases creatively.", True),
    ("boy math", "The same, aimed back.", True),
    ("roman empire", "The thing you think about constantly.", True),
    ("hot girl summer", "A summer of confidence.", False),
    ("delulu is the solulu", "Delusion is the solution.", True),
    ("manifesting", "Willing something into existence.", False),
    ("periodt", "Period, with emphasis.", False),
    ("tea", "Gossip.", False),
    ("spill the tea", "Share the gossip.", False),
    ("shade", "A subtle insult.", False),
    ("receipts", "Evidence.", False),
    ("snatched", "Looking great.", False),
    ("slaps", "Is excellent, of music.", False),
    ("banger", "An excellent song.", False),
    ("hits different", "Feels uniquely good.", False),
    ("fire", "Excellent.", False),
    ("lit", "Exciting.", False),
    ("GOAT", "Greatest of all time.", False),
    ("goated", "Being the greatest.", False),
    ("bruh", "Disbelief.", False),
    ("bruh moment", "A moment of disbelief.", False),
    ("I'm dead", "That's hilarious.", False),
    ("screaming", "That's hilarious.", False),
    ("sending me", "Making me laugh uncontrollably.", True),
    ("not me", "A self-aware confession. 'Not me crying.'", True),
    ("it's the ___ for me", "Pointing out the notable detail.", True),
    ("bestie", "Friend. Or stranger. Affectionately.", False),
    ("valid", "Acceptable.", False),
    ("so real", "Extremely relatable.", True),
    ("you're so real for that", "That was relatable.", True),
    ("so true bestie", "Ironic agreement.", True),
    ("didn't ask", "Dismissal.", False),
    ("who asked", "Dismissal.", False),
    ("big yikes", "Very awkward.", False),
    ("oof", "Ouch.", False),
    ("and I oop", "Caught off guard.", True),
    ("sksksk", "VSCO girl laughter.", True),
    ("VSCO girl", "Scrunchies, Hydro Flasks, 2019.", True),
    ("e-girl", "Alt internet girl aesthetic.", False),
    ("e-boy", "Alt internet boy aesthetic.", False),
    ("bombastic side eye", "A dramatic look of judgement.", True),
    ("criminal offensive side eye", "The full meme.", True),
    ("side eye", "A look of judgement.", False),
    ("gagged", "Shocked. Impressed.", True),
    ("menace", "A chaotic person.", False),
    ("menace to society", "A very chaotic person.", False),
    ("ship", "Want two people to be together.", False),
    ("OTP", "One true pairing.", True),
    ("headcanon", "A personal fan theory.", True),
    ("cat behavior", "Acting like a cat.", True),
    ("he's him", "He's the real deal.", True),
    ("she's her", "She's the real deal.", True),
    ("tweaking", "Acting irrationally.", True),
    ("bro is tweaking", "He's acting irrationally.", True),
    ("the audacity", "The nerve.", False),
    ("gaslight gatekeep girlboss", "The ironic feminine villainy triad.", True),
    ("gatekeep", "Withhold the good stuff.", False),
    ("girlboss", "Ambitious woman, ironically.", False),
    ("chad", "A confident, dominant man.", False),
    ("gigachad", "Extremely so.", False),
    ("grindset", "Hustle mindset.", False),
    ("sigma grindset", "Hustle mindset, ironic.", True),
    ("what the sigma", "What the heck, brainrot edition.", True),
    ("alpha", "The dominant type.", False),
    ("beta", "The submissive type.", False),
    ("npc streamer", "Streamers who react to gifts with stock phrases.", True),
    ("ice cream so good", "The NPC streamer's catchphrase.", True),
    ("gang gang", "Another NPC streamer catchphrase.", True),
    ("erm", "Um, but condescending.", True),
    ("what the flip", "What the heck, censored.", True),
    ("bing chilling", "John Cena, Chinese, ice cream.", True),
    ("glizzy", "A hot dog.", True),
    ("smellmaxxing", "Teens buying far too much cologne.", True),
    ("heightmaxxing", "Trying to get taller.", True),
    ("gymmaxxing", "Trying to get jacked.", True),
    ("mog", "To outshine someone.", False),
    ("mogged", "Outshone.", False),
    ("finna", "Going to.", False),
    ("boutta", "About to.", False),
    ("ghosted", "Got ghosted.", False),
    ("left on read", "Message seen. Not answered.", False),
    ("dry texter", "A boring texter.", False),
    ("curve", "Reject someone.", True),
    ("cuffing season", "Winter coupling season.", False),
    ("bae", "Partner.", False),
    ("thirst trap", "A post designed for attention.", False),
    ("flex", "Show off.", False),
    ("weird flex but ok", "Odd thing to brag about.", False),
    ("big mood", "Very relatable.", False),
    ("mood", "Relatable.", False),
    ("snack", "An attractive person.", False),
    ("wig", "So good the wig flew off.", True),
    ("shook", "Shocked.", False),
    ("extra", "Over the top.", False),
    ("basic", "Unoriginal.", False),
    ("boujee", "Fancy.", False),
    ("yeet", "Throw. Or just shout.", False),
    ("fam", "Family. Friends.", False),
    ("savage", "Brutally honest.", False),
    ("ok boomer", "Dismissing the old.", False),
    ("zoomer", "A Gen Z person.", False),
    ("ipad kid", "A child raised by a tablet.", True),
    ("sephora kid", "A ten-year-old buying retinol.", True),
    ("skibidi toilet", "The original brainrot series.", False),
    ("camera man", "The Skibidi Toilet protagonist faction.", True),
    ("speaker man", "Camera man's colleague.", True),
    ("tv man", "The upgrade.", True),
    ("noob", "A beginner.", False),
    ("op", "Overpowered.", False),
    ("nerf", "Weaken.", False),
    ("buff", "Strengthen.", False),
    ("clown", "A fool. 🤡", False),
    ("cornball", "An embarrassing person.", True),
    ("corny", "Cheesy.", False),
    ("opp", "An enemy.", True),
    ("that's crazy", "Dismissive acknowledgement.", False),
    ("wild", "Surprising.", False),
    ("goes hard", "Is excellent.", False),
    ("goes crazy", "Is excellent.", False),
    ("certified banger", "Definitely excellent.", False),
    ("hood classic", "A beloved song.", True),
    ("AI slop", "Low-effort AI content.", True),
    ("slop", "Low-effort content.", True),
    ("giving", "Evoking. 'It's giving 2016.'", True),
    ("lore accurate", "True to the backstory.", True),
    ("nah he tweakin", "He's lost it.", True),
    ("bro thinks he's", "Bro thinks he's the main character.", True),
    ("the way", "Emphasising something. 'The way I ran.'", True),
    ("purr", "Period, with more attitude.", True),
    ("mother of", "Prefix for an icon. 'Mother of pop.'", True),
    ("hard", "Cool. 'That's hard.'", True),

    # ── Italian brainrot ──────────────────────────────────────────────────
    ("tralalero tralala", "A shark in Nikes. Yes, really.", False),
    ("bombardiro crocodilo", "Crocodile-bomber hybrid.", False),
    ("tung tung tung sahur", "An Indonesian Ramadan wake-up drum, alive.", True),
    ("ballerina cappuccina", "Ballerina, cappuccino for a head.", False),
    ("brr brr patapim", "Tree-legged proboscis creature.", True),
    ("chimpanzini bananini", "Chimp in a banana.", True),
    ("lirili larila", "Cactus elephant in sandals.", True),
    ("cappuccino assassino", "Assassin coffee cup.", True),
    ("boneca ambalabu", "Frog with a tyre for a body.", True),
    ("trippi troppi", "Shrimp-cat thing.", True),
    ("bombombini gusini", "Bomber goose. Bombardiro's cousin.", True),
    ("frigo camelo", "Camel with a fridge for a body.", True),
    ("glorbo fruttodrillo", "Watermelon crocodile.", True),
    ("burbaloni luliloli", "Coconut capybara.", True),
    ("la vaca saturno saturnita", "A cow with Saturn for a body.", True),
    ("orangutini ananassini", "Pineapple orangutan.", True),
    ("trulimero trulicina", "Fish-headed cat.", True),
    ("girafa celestre", "Celestial giraffe.", True),
    ("bobrito bandito", "Bandit beaver.", True),
    ("talpa di fero", "Iron mole.", True),
    ("espressona signora", "Espresso lady.", True),
    ("rhino toasterino", "Rhino toaster.", True),
    ("cocofanto elefanto", "Coconut elephant.", True),
    ("piccione macchina", "Pigeon car.", True),
    ("chef crabracadabra", "Crab chef.", True),
]

# (term, note, tricky)
FAKE = [
    # ── invented roots ────────────────────────────────────────────────────
    ("grimzo", "Invented. Sounds plausible, means nothing.", False),
    ("snorpling", "Invented. Not a thing. Never was.", False),
    ("flonkered", "Invented. Sounds like something. It is not.", False),
    ("drimpy", "Invented. Zero usage anywhere.", False),
    ("zorpo", "Invented. No lore, no meme, no nothing.", False),
    ("skrimblo", "Invented. Pure nonsense, correctly identified.", False),
    ("blorpo", "Invented.", False),
    ("glimbo", "Invented.", False),
    ("smorp", "Invented.", False),
    ("florp", "Invented.", False),
    ("quimble", "Invented.", False),
    ("dringle", "Invented.", False),
    ("crumbo", "Invented.", False),
    ("blungus", "Invented.", False),
    ("drongus", "Invented.", False),
    ("sporgle", "Invented.", False),
    ("twizzled", "Invented.", False),
    ("frumple", "Invented.", False),
    ("grumbo", "Invented.", False),
    ("snizzle", "Invented.", False),
    ("plorb", "Invented.", False),
    ("zimbo", "Invented.", False),
    ("krimble", "Invented.", False),
    ("vronk", "Invented.", False),
    ("shlorp", "Invented.", False),
    ("gronkled", "Invented.", False),
    ("skronked", "Invented.", False),
    ("yorped", "Invented.", False),
    ("nurp", "Invented.", False),
    ("flerp", "Invented.", False),
    ("glooped", "Invented.", False),
    ("drungle", "Invented.", False),
    ("plonkers only", "Invented. Not a thing.", False),
    ("yeetus deluxe", "Invented. Yeet is real; the deluxe edition is not.", False),
    ("vibecrashing", "Invented. You were pattern-matching, weren't you.", False),

    # ── real pattern, invented root ───────────────────────────────────────
    ("crumbmaxxing", "Invented. -maxxing is real, this one isn't.", True),
    ("frizzlemaxxing", "Invented. The suffix does a lot of heavy lifting.", True),
    ("bonkmaxxing", "Invented. Another suffix trap.", True),
    ("sneedmaxxing", "Invented. The suffix carried it, didn't it.", True),
    ("blorpmaxxing", "Invented.", True),
    ("noobmaxxing", "Invented. Both halves real, the compound isn't.", True),
    ("tastemaxxing", "Invented. Smellmaxxing is real. This is not.", True),
    ("hearmaxxing", "Invented.", True),
    ("gigafumbling", "Invented. Fumbling is real, the giga tier isn't.", True),
    ("snorp-pilled", "Invented. -pilled is a real pattern.", True),
    ("flonk era", "Invented.", False),
    ("drimpcore", "Invented. -core is real, drimp is not.", True),
    ("cottagecrust", "Invented. Cottagecore's evil twin.", True),
    ("zorp check", "Invented.", False),
    ("skrimb energy", "Invented.", False),
    ("plonk szn", "Invented.", False),
    ("grommet szn", "Invented. Szn is real, grommet szn is not.", True),
    ("frizz arc", "Invented.", False),
    ("crimb-coded", "Invented. -coded is a real pattern.", True),
    ("grimz behavior", "Invented.", False),
    ("grumbo moment", "Invented.", False),
    ("florp hours", "Invented.", False),
    ("twizzle farming", "Invented. Aura farming is real.", True),
    ("sporgle god", "Invented.", False),
    ("snizzle rights", "Invented.", False),
    ("plorb privilege", "Invented.", False),
    ("krimble points", "Invented. Aura points are real.", True),
    ("vronk activities", "Invented.", False),

    # ── near-misses of real terms (the best traps) ────────────────────────
    ("skibidi tax", "Invented. Two real terms welded together.", True),
    ("wumbo tax", "Invented. Fanum tax is real. This is not.", True),
    ("phantom tax", "Invented. A mishearing that never caught on.", True),
    ("clanker tax", "Invented.", True),
    ("huzz tax", "Invented.", True),
    ("rizz rebate", "Invented.", True),
    ("fanum refund", "Invented.", True),
    ("skibidi surcharge", "Invented.", True),
    ("aura laundering", "Invented. Aura points are real; laundering them isn't.", True),
    ("aura audit", "Invented.", True),
    ("aura pension", "Invented.", True),
    ("aura mortgage", "Invented.", True),
    ("aura fishing", "Invented. Farming is real. Fishing is not.", True),
    ("aura mining", "Invented.", True),
    ("aura foraging", "Invented.", True),
    ("gyatt gap", "Invented.", True),
    ("mog debt", "Invented.", True),
    ("yap ledger", "Invented.", True),
    ("yapology", "Invented.", True),
    ("yappuccino", "Invented. Should be real. Isn't.", True),
    ("cook check", "Invented.", True),
    ("delulu decree", "Invented.", True),
    ("delulu is the trululu", "Invented. Solulu is real.", True),
    ("trululu", "Invented.", True),
    ("grass credit", "Invented.", True),
    ("touch drywall", "Invented. Grass is real. Drywall is not.", True),
    ("touch gravel", "Invented.", True),
    ("touch asphalt", "Invented.", True),
    ("touch ceiling", "Invented.", True),
    ("chronically offline", "Invented. The opposite of a real one.", True),
    ("terminally offline", "Invented.", True),
    ("bed thriving", "Invented. Bed rotting is real.", True),
    ("floor rotting", "Invented.", True),
    ("goblin tier", "Invented. Goblin mode is real.", True),
    ("troll mode", "Invented. Goblin mode is real.", True),
    ("orc mode", "Invented.", True),
    ("gremlin math", "Invented. Girl math is real.", True),
    ("cat math", "Invented.", True),
    ("girl physics", "Invented. Girl math is real.", True),
    ("girl geometry", "Invented.", True),
    ("boy chemistry", "Invented. Boy math is real.", True),
    ("girl banquet", "Invented. Girl dinner is real.", True),
    ("roman republic", "Invented. The Empire is real, as slang.", True),
    ("greek empire", "Invented.", True),
    ("byzantine empire", "Invented, as slang. Real, as history.", True),
    ("canon leak", "Invented. Canon event is real.", True),
    ("lore patch", "Invented.", True),
    ("core rumor", "Invented. Core memory is real.", True),
    ("main character loan", "Invented.", True),
    ("cameo energy", "Invented. Main character energy is real.", True),
    ("villain intermission", "Invented. Villain era is real.", True),
    ("villain prequel", "Invented.", True),
    ("flop insurance", "Invented.", True),
    ("flop intermission", "Invented.", True),
    ("slay license", "Invented.", True),
    ("serve permit", "Invented.", True),
    ("ate certificate", "Invented.", True),
    ("crumb audit", "Invented. Ate and left no crumbs is real.", True),
    ("chewed", "Invented, as praise. Ate is real.", True),
    ("bestie clause", "Invented.", True),
    ("twin clause", "Invented.", True),
    ("ong invoice", "Invented.", True),
    ("fr receipt", "Invented.", True),
    ("cap warranty", "Invented.", True),
    ("no hat", "Invented. No cap is real.", True),
    ("no visor", "Invented.", True),
    ("medium yikes", "Invented. Big yikes is real.", True),
    ("small yikes", "Invented.", True),
    ("yikes squared", "Invented.", True),
    ("oof cubed", "Invented.", True),
    ("and I aap", "Invented. And I oop is real.", True),
    ("skskskt", "Invented. Close. Not close enough.", True),
    ("VSCO dad", "Invented. VSCO girl is real.", True),
    ("e-uncle", "Invented. E-girl and e-boy are real.", True),
    ("e-grandma", "Invented.", True),
    ("shy launch", "Invented. Soft launch is real.", True),
    ("whisper launch", "Invented.", True),
    ("situationboat", "Invented. Situationship is real.", True),
    ("relationshop", "Invented.", True),
    ("whispering stage", "Invented. Talking stage is real.", True),
    ("mumbling stage", "Invented.", True),
    ("down mediocre", "Invented. Down bad is real.", True),
    ("up bad", "Invented.", True),
    ("domesticated", "Invented, as slang. Feral is real.", True),
    ("gloomscrolling", "Invented. Doomscrolling is real.", True),
    ("doomhovering", "Invented.", True),
    ("croquette", "Invented, as an aesthetic. Coquette is real. Croquette is a potato.", True),
    ("tidy girl", "Invented. Clean girl is real.", True),
    ("rinsed girl", "Invented.", True),
    ("very brash very reckless", "Invented. Very demure very mindful is real.", True),
    ("brat monsoon", "Invented. Brat summer is real.", True),
    ("lukewarm girl summer", "Invented. Hot girl summer is real.", True),
    ("commat", "Invented. Periodt is real.", True),
    ("semicolont", "Invented.", True),
    ("spill the broth", "Invented. Tea is real.", True),
    ("spill the cocoa", "Invented.", True),
    ("throw umbra", "Invented. Throw shade is real.", True),
    ("invoices", "Invented, as slang. Receipts is real.", True),
    ("coupons", "Invented, as slang.", True),
    ("grabbed", "Invented, as praise. Snatched is real.", True),
    ("pokes", "Invented, of music. Slaps is real.", True),
    ("thumper", "Invented. Banger is real.", True),
    ("hits similar", "Invented. Hits different is real.", True),
    ("misses different", "Invented.", True),
    ("the LLAMA", "Invented. The GOAT is real.", True),
    ("the YAK", "Invented.", True),
    ("brih", "Invented. Bruh is real.", True),
    ("bruhm", "Invented.", True),
    ("I'm cremated", "Invented. I'm dead is real.", True),
    ("mediumie", "Invented. Bestie is real.", True),
    ("okayie", "Invented.", True),
    ("expired", "Invented, as slang. Valid is real.", True),
    ("modest side eye", "Invented. Bombastic side eye is real.", True),
    ("bombastic front eye", "Invented.", True),
    ("hiccuped", "Invented, as slang. Gagged is real.", True),
    ("the yacht", "Invented, as slang. Ship is real.", True),
    ("OTQ", "Invented. OTP is real.", True),
    ("headsequel", "Invented. Headcanon is real.", True),
    ("hamster behavior", "Invented. Cat behavior is real.", True),
    ("gecko behavior", "Invented.", True),
    ("he's whom", "Invented. He's him is real.", True),
    ("tweakmaxxing", "Invented.", True),
    ("the humility", "Invented. The audacity is real.", True),
    ("gaslight gatekeep grandpa", "Invented.", True),
    ("thad", "Invented. Chad is real.", True),
    ("gigathad", "Invented.", True),
    ("napset", "Invented. Grindset is real.", True),
    ("loungeset", "Invented.", True),
    ("what the omega", "Invented. What the sigma is real.", True),
    ("what the delta", "Invented.", True),
    ("epsilon male", "Invented. Alpha, beta, sigma are real.", True),
    ("lambda male", "Invented.", True),
    ("pc streamer", "Invented. NPC streamer is real.", True),
    ("soup so good", "Invented. Ice cream so good is real.", True),
    ("ice cream so mid", "Invented.", True),
    ("urm", "Invented. Erm is real.", True),
    ("what the flop", "Invented. What the flip is real.", True),
    ("bing freezing", "Invented. Bing chilling is real.", True),
    ("glizzard", "Invented. Glizzy is real.", True),
    ("finto", "Invented. Finna is real.", True),
    ("left on skim", "Invented. Left on read is real.", True),
    ("damp texter", "Invented. Dry texter is real.", True),
    ("humid texter", "Invented.", True),
    ("ziptie season", "Invented. Cuffing season is real.", True),
    ("hunger trap", "Invented. Thirst trap is real.", True),
    ("thirst net", "Invented.", True),
    ("weird stretch but ok", "Invented. Weird flex but ok is real.", True),
    ("large mood", "Invented. Big mood is real.", True),
    ("grand mood", "Invented.", True),
    ("appetiser", "Invented, as slang. Snack is real.", True),
    ("toupee", "Invented, as slang. Wig is real.", True),
    ("stirred", "Invented, as slang. Shook is real.", True),
    ("surplus", "Invented, as slang. Extra is real.", True),
    ("intermediate", "Invented, as slang. Basic is real.", True),
    ("civil", "Invented, as slang. Savage is real.", True),
    ("ok gen x", "Invented. Ok boomer is real.", True),
    ("kindle kid", "Invented. iPad kid is real.", True),
    ("calculator kid", "Invented.", True),
    ("walgreens kid", "Invented. Sephora kid is real.", True),
    ("ohio mini boss", "Invented. Ohio final boss is real.", True),
    ("ohio tutorial boss", "Invented.", True),
    ("ohio passport", "Invented.", True),
    ("ohio embassy", "Invented.", True),
    ("indiana", "Invented, as slang. Ohio is real.", True),
    ("nebraska", "Invented, as slang.", True),
    ("delaware", "Invented, as slang.", True),
    ("eight nine", "Invented. Six seven is real.", True),
    ("four five", "Invented.", True),
    ("big front", "Invented. Big back is real.", True),
    ("small back", "Invented.", True),
    ("unc diploma", "Invented. Unc status is real.", True),
    ("rizzington", "Invented. Rizzler is real.", True),
    ("rizztopher", "Invented.", True),
    ("talent issue", "Invented. Skill issue is real.", True),
    ("luck issue", "Invented.", True),
    ("GB", "Invented. GG is real.", True),
    ("bonzo", "Invented. Bozo is real.", True),
    ("roofed", "Invented. Based is real.", True),
    ("let him bake", "Invented. Let him cook is real.", True),
    ("let him fry", "Invented.", True),
    ("let him simmer", "Invented.", True),
    ("sautéed", "Invented, as slang. Cooked is real.", True),
    ("braised", "Invented, as slang.", True),
    ("poached", "Invented, as slang.", True),
    ("diced", "Invented, as slang. Chopped is real.", True),
    ("minced", "Invented, as slang.", True),
    ("julienned", "Invented, as slang.", True),
    ("frosting", "Invented, as slang. Glazing is real.", True),
    ("crashing in", "Invented. Crashing out is real.", True),
    ("crashing sideways", "Invented.", True),
    ("fractioned", "Invented. Ratioed is real.", True),
    ("it's lending", "Invented. It's giving is real.", True),
    ("it's borrowing", "Invented.", True),
    ("cousin is cousining", "Invented. Mother is mothering is real.", True),
    ("aunt is aunting", "Invented.", True),
    ("misread the syllabus", "Invented. Understood the assignment is real.", True),
    ("skipped the assignment", "Invented.", True),
    ("living rent controlled", "Invented. Rent free is real.", True),
    ("subletting", "Invented, as slang.", True),
    ("vibe audit", "Invented. Vibe check is real.", True),
    ("vibe census", "Invented.", True),
    ("simpington", "Invented. Simp is real.", True),
    ("the ack", "Invented. The ick is real.", True),
    ("the eck", "Invented.", True),
    ("taupe flag", "Invented. Beige flag is real.", True),
    ("mauve flag", "Invented.", True),
    ("teal flag", "Invented.", True),
    ("phantoming", "Invented. Ghosting is real.", True),
    ("spectering", "Invented.", True),
    ("croutoning", "Invented. Breadcrumbing is real.", True),
    ("baguetting", "Invented.", True),
    ("AI broth", "Invented. AI slop is real.", True),
    ("AI porridge", "Invented.", True),
    ("goes medium", "Invented. Goes hard is real.", True),
    ("goes firm", "Invented.", True),
    ("mini boss energy", "Invented.", True),
    ("hood remix", "Invented, as praise. Hood classic is real.", True),

    # ── fake Italian brainrot ─────────────────────────────────────────────
    ("prambulo fantastico", "Fake Italian brainrot. Convincing, though.", True),
    ("spaghettini yappini", "Fake Italian brainrot. Two real words, no real meme.", True),
    ("bombolino trattorio", "Fake. Close cousin of a real one, which is the trap.", True),
    ("trombonini gelatini", "Fake Italian brainrot. Entirely fabricated.", True),
    ("rizzardo bambino", "Fake. Real prefix, invented character.", True),
    ("glorpini crocodilini", "Fake. Deliberately near-miss on a real one.", True),
    ("arancino assassino", "Fake. Cappuccino assassino is real. This is a rice ball.", True),
    ("mozzarello scooterino", "Fake Italian brainrot.", True),
    ("gelato pistolero", "Fake Italian brainrot.", True),
    ("lasagnini bambini", "Fake Italian brainrot.", True),
    ("espressino turbino", "Fake. Espressona signora is real.", True),
    ("frittata karatista", "Fake Italian brainrot.", True),
    ("gnocchi pilota", "Fake Italian brainrot.", True),
    ("risotto bandito", "Fake. Bobrito bandito is real.", True),
    ("panini tsunami", "Fake Italian brainrot.", True),
    ("biscotti robotti", "Fake Italian brainrot.", True),
    ("cannoli anomali", "Fake Italian brainrot.", True),
    ("tiramisu kung fu", "Fake Italian brainrot.", True),
    ("prosciutto astronauto", "Fake Italian brainrot.", True),
    ("polenta violenta", "Fake Italian brainrot.", True),
    ("ravioli ninja", "Fake Italian brainrot.", True),
    ("calzone ciclone", "Fake Italian brainrot.", True),
    ("burrata pirata", "Fake Italian brainrot.", True),
    ("pesto manifesto", "Fake Italian brainrot.", True),
    ("linguine houdini", "Fake Italian brainrot.", True),
    ("capellini zeppelini", "Fake Italian brainrot.", True),
    ("focaccia ballista", "Fake Italian brainrot.", True),
    ("tortellini martini", "Fake Italian brainrot.", True),
    ("gorgonzola gondola", "Fake Italian brainrot.", True),
    ("bruschetta rocketta", "Fake Italian brainrot.", True),
    ("tagliatelle tarantella", "Fake Italian brainrot.", True),
    ("cannellini mussolini", "Fake. And no.", False),
]

# Anything on this list fails the build. 13+ means 13+.
BANNED = {"goon", "gooning", "edging", "tuah", "sybau", "dih", "pmo", "diddy", "hawk"}


def main():
    terms = []
    seen = set()
    problems = []

    for is_real, rows in ((True, REAL), (False, FAKE)):
        for text, note, tricky in rows:
            key = text.lower().strip()
            if key in seen:
                problems.append("duplicate: %s" % text)
            seen.add(key)
            if len(text) > 28:
                problems.append("too long for the card: %s" % text)
            for bad in BANNED:
                if re.search(r"\b" + re.escape(bad) + r"\b", key):
                    problems.append("banned for 13+: %s" % text)
            terms.append({"t": text, "r": is_real, "k": bool(tricky), "n": note})

    # "cannellini mussolini" is a name joke that fails the no-real-people rule.
    terms = [t for t in terms if "mussolini" not in t["t"]]

    if problems:
        print("\n".join(problems))
        sys.exit(1)

    real = sum(1 for t in terms if t["r"])
    fake = len(terms) - real
    tricky = sum(1 for t in terms if t["k"])

    payload = {"version": VERSION, "updated": UPDATED, "terms": terms}
    # Same file for both builds: the iOS bundle and the web root.
    web_out = os.path.join(os.path.dirname(os.path.dirname(OUT)), "..", "deck.json")
    for path in (OUT, os.path.normpath(web_out)):
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with io.open(path, "w", encoding="utf-8") as f:
            json.dump(payload, f, ensure_ascii=False, indent=0, separators=(",", ":"))
        print("wrote %s" % os.path.relpath(path))
    print("  real %d · fake %d · total %d · tricky %d (%d%%)"
          % (real, fake, len(terms), tricky, round(tricky * 100 / len(terms))))


if __name__ == "__main__":
    main()
